# Target specific macros
TARGET = nxt_OSEK
TARGET_SOURCES = \
	./src/tasks.c \
	./src/data_receive.c \
	./src/movement.c \
	./src/display.c
TOPPERS_OSEK_OIL_SOURCE = ./nxt.oil
USER_INC_PATH = ./inc

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
